export const ct_ct_002 = [
  {
    type: "중분류",
    typeCode: "ct_ct_002",
    value: "자켓/점퍼",
    valueCode: "ot_jk_000",
  },
  {
    type: "중분류",
    typeCode: "ct_ct_002",
    value: "코트/트렌치",
    valueCode: "ot_ct_000",
  },
  {
    type: "중분류",
    typeCode: "ct_ct_002",
    value: "패딩류",
    valueCode: "ot_pd_000",
  },
  {
    type: "중분류",
    typeCode: "ct_ct_002",
    value: "맨투맨/후드티",
    valueCode: "tp_sw_000",
  },
  {
    type: "중분류",
    typeCode: "ct_ct_002",
    value: "셔츠/블라우스",
    valueCode: "st_sh_000",
  },
  {
    type: "중분류",
    typeCode: "ct_ct_002",
    value: "티셔츠",
    valueCode: "tp_ts_000",
  },
  {
    type: "중분류",
    typeCode: "ct_ct_002",
    value: "니트",
    valueCode: "tp_kt_000",
  },
  {
    type: "중분류",
    typeCode: "ct_ct_002",
    value: "팬츠",
    valueCode: "bt_pt_000",
  },
  {
    type: "중분류",
    typeCode: "ct_ct_002",
    value: "레깅스",
    valueCode: "bt_lg_000",
  },
  {
    type: "중분류",
    typeCode: "ct_ct_002",
    value: "스커트",
    valueCode: "bt_sk_000",
  },
  {
    type: "중분류",
    typeCode: "ct_ct_002",
    value: "원피스",
    valueCode: "op_ds_000",
  },
  {
    type: "중분류",
    typeCode: "ct_ct_002",
    value: "점프수트",
    valueCode: "op_js_000",
  },
  {
    type: "중분류",
    typeCode: "ct_ct_002",
    value: "점프수트",
    valueCode: "op_js_000",
  },
];
