export const ct_ct_003 = [
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '블레이저',
    valueCode: 'ot_jk_001',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '트위드 자켓',
    valueCode: 'ot_jk_002',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '데님 자켓',
    valueCode: 'ot_jk_003',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '레더 자켓',
    valueCode: 'ot_jk_004',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '후드집업',
    valueCode: 'ot_jk_005',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '바람막이',
    valueCode: 'ot_jk_006',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '야상',
    valueCode: 'ot_jk_007',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '후리스',
    valueCode: 'ot_jk_008',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '퍼',
    valueCode: 'ot_jk_009',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '무스탕',
    valueCode: 'ot_jk_010',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '기타',
    valueCode: 'ot_jk_011',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '코트',
    valueCode: 'ot_ct_001',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '트렌치 코트',
    valueCode: 'ot_ct_002',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '패딩',
    valueCode: 'ot_pd_001',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '경량 패딩',
    valueCode: 'ot_pd_002',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '조끼 패딩',
    valueCode: 'ot_pd_003',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '맨투맨',
    valueCode: 'tp_sw_001',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '후드티',
    valueCode: 'tp_sw_002',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '블라우스',
    valueCode: 'st_sh_001',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '셔츠',
    valueCode: 'st_sh_002',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '니트 풀오버',
    valueCode: 'tp_kt_001',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '가디건',
    valueCode: 'tp_kt_002',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '터틀넥',
    valueCode: 'tp_kt_003',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '니트베스트/뷔스티에',
    valueCode: 'tp_kt_004',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '스키니',
    valueCode: 'bt_pt_001',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '스트레이트',
    valueCode: 'bt_pt_002',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '부츠컷',
    valueCode: 'bt_pt_003',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '와이드',
    valueCode: 'bt_pt_004',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '조거',
    valueCode: 'bt_pt_005',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '기타',
    valueCode: 'bt_pt_006',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '미니',
    valueCode: 'bt_sk_001',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '미디',
    valueCode: 'bt_sk_002',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '롱',
    valueCode: 'bt_sk_003',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '미니',
    valueCode: 'op_ds_001',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '미디',
    valueCode: 'op_ds_002',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '롱',
    valueCode: 'op_ds_003',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '단독',
    valueCode: 'op_js_001',
  },
  {
    type: '소분류',
    typeCode: 'ct_ct_003',
    value: '레이어드',
    valueCode: 'op_js_002',
  },
];
