export const detail = [
  {
    type: '계절',
    typeCode: 'de_se_000',
    value: '봄',
    valueCode: 'de_se_001',
  },
  {
    type: '계절',
    typeCode: 'de_se_000',
    value: '여름',
    valueCode: 'de_se_002',
  },
  {
    type: '계절',
    typeCode: 'de_se_000',
    value: '가을',
    valueCode: 'de_se_003',
  },
  {
    type: '계절',
    typeCode: 'de_se_000',
    value: '겨울',
    valueCode: 'de_se_004',
  },
  {
    type: '==',
    typeCode: '==',
    value: '==',
    valueCode: '==',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '흰색',
    valueCode: 'de_co_001',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '크림',
    valueCode: 'de_co_002',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '베이지',
    valueCode: 'de_co_003',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '연회색',
    valueCode: 'de_co_004',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '진회색',
    valueCode: 'de_co_005',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '검정',
    valueCode: 'de_co_006',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '연분홍',
    valueCode: 'de_co_007',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '레몬',
    valueCode: 'de_co_008',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '텐저린',
    valueCode: 'de_co_009',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '연두',
    valueCode: 'de_co_010',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '하늘색',
    valueCode: 'de_co_011',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '연보라',
    valueCode: 'de_co_012',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '분홍',
    valueCode: 'de_co_013',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '노랑',
    valueCode: 'de_co_014',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '주황',
    valueCode: 'de_co_015',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '초록',
    valueCode: 'de_co_016',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '파랑',
    valueCode: 'de_co_017',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '보라',
    valueCode: 'de_co_018',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '빨강',
    valueCode: 'de_co_019',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '카멜',
    valueCode: 'de_co_020',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '브라운',
    valueCode: 'de_co_021',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '카키',
    valueCode: 'de_co_022',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '네이비',
    valueCode: 'de_co_023',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '와인',
    valueCode: 'de_co_024',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '골드',
    valueCode: 'de_co_025',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '실버',
    valueCode: 'de_co_026',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '네온',
    valueCode: 'de_co_027',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '민트',
    valueCode: 'de_co_028',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '소라',
    valueCode: 'de_co_029',
  },
  {
    type: '컬러',
    typeCode: 'de_co_000',
    value: '코랄',
    valueCode: 'de_co_030',
  },
  {
    type: '==',
    typeCode: '==',
    value: '==',
    valueCode: '==',
  },
  {
    type: '기장',
    typeCode: 'de_tl_000',
    value: '크롭 기장',
    valueCode: 'de_tl_001',
  },
  {
    type: '기장',
    typeCode: 'de_tl_000',
    value: '일반 기장',
    valueCode: 'de_tl_002',
  },
  {
    type: '기장',
    typeCode: 'de_tl_000',
    value: '롱 기장',
    valueCode: 'de_tl_003',
  },
  {
    type: '==',
    typeCode: '==',
    value: '==',
    valueCode: '==',
  },
  {
    type: '소매 기장',
    typeCode: 'de_sl_000',
    value: '민 소매',
    valueCode: 'de_sl_001',
  },
  {
    type: '소매 기장',
    typeCode: 'de_sl_000',
    value: '숏 슬리브',
    valueCode: 'de_sl_002',
  },
  {
    type: '소매 기장',
    typeCode: 'de_sl_000',
    value: '5부-7부 슬리브',
    valueCode: 'de_sl_003',
  },
  {
    type: '소매 기장',
    typeCode: 'de_sl_000',
    value: '롱 슬리브',
    valueCode: 'de_sl_004',
  },
  {
    type: '==',
    typeCode: '==',
    value: '==',
    valueCode: '==',
  },
  {
    type: '하의 기장',
    typeCode: 'dt_bl_000',
    value: '1-4부/미니',
    valueCode: 'dt_bl_001',
  },
  {
    type: '하의 기장',
    typeCode: 'dt_bl_000',
    value: '5부/미디',
    valueCode: 'dt_bl_002',
  },
  {
    type: '하의 기장',
    typeCode: 'dt_bl_000',
    value: '7부/미디',
    valueCode: 'dt_bl_003',
  },
  {
    type: '하의 기장',
    typeCode: 'dt_bl_000',
    value: '8-10부/롱',
    valueCode: 'dt_bl_004',
  },
  {
    type: '==',
    typeCode: '==',
    value: '==',
    valueCode: '==',
  },
  {
    type: '소재',
    typeCode: 'de_mt_000',
    value: '면',
    valueCode: 'de_mt_001',
  },
  {
    type: '소재',
    typeCode: 'de_mt_000',
    value: '린넨',
    valueCode: 'de_mt_002',
  },
  {
    type: '소재',
    typeCode: 'de_mt_000',
    value: '나일론/폴리',
    valueCode: 'de_mt_003',
  },
  {
    type: '소재',
    typeCode: 'de_mt_000',
    value: '레이온',
    valueCode: 'de_mt_004',
  },
  {
    type: '소재',
    typeCode: 'de_mt_000',
    value: '니트/울/캐시미어',
    valueCode: 'de_mt_005',
  },
  {
    type: '소재',
    typeCode: 'de_mt_000',
    value: '퍼',
    valueCode: 'de_mt_006',
  },
  {
    type: '소재',
    typeCode: 'de_mt_000',
    value: '트위드',
    valueCode: 'de_mt_007',
  },
  {
    type: '소재',
    typeCode: 'de_mt_000',
    value: '실크',
    valueCode: 'de_mt_008',
  },
  {
    type: '소재',
    typeCode: 'de_mt_000',
    value: '데님',
    valueCode: 'de_mt_009',
  },
  {
    type: '소재',
    typeCode: 'de_mt_000',
    value: '가죽',
    valueCode: 'de_mt_010',
  },
  {
    type: '소재',
    typeCode: 'de_mt_000',
    value: '스웨이드',
    valueCode: 'de_mt_011',
  },
  {
    type: '소재',
    typeCode: 'de_mt_000',
    value: '벨벳',
    valueCode: 'de_mt_012',
  },
  {
    type: '소재',
    typeCode: 'de_mt_000',
    value: '쉬폰',
    valueCode: 'de_mt_013',
  },
  {
    type: '소재',
    typeCode: 'de_mt_000',
    value: '코듀로이',
    valueCode: 'de_mt_014',
  },
  {
    type: '소재',
    typeCode: 'de_mt_000',
    value: '기타',
    valueCode: 'de_mt_015',
  },
  {
    type: '==',
    typeCode: '==',
    value: '==',
    valueCode: '==',
  },
  {
    type: '원피스 기장',
    typeCode: 'dt_ol_000',
    value: '미니',
    valueCode: 'dt_ol_001',
  },
  {
    type: '원피스 기장',
    typeCode: 'dt_ol_000',
    value: '미디',
    valueCode: 'dt_ol_002',
  },
  {
    type: '원피스 기장',
    typeCode: 'dt_ol_000',
    value: '롱',
    valueCode: 'dt_ol_003',
  },
  {
    type: '==',
    typeCode: '==',
    value: '==',
    valueCode: '==',
  },
  {
    type: '패턴',
    typeCode: 'de_pt_000',
    value: '무지',
    valueCode: 'de_pt_001',
  },
  {
    type: '패턴',
    typeCode: 'de_pt_000',
    value: '체크',
    valueCode: 'de_pt_002',
  },
  {
    type: '패턴',
    typeCode: 'de_pt_000',
    value: '스트라이프',
    valueCode: 'de_pt_003',
  },
  {
    type: '패턴',
    typeCode: 'de_pt_000',
    value: '프린트',
    valueCode: 'de_pt_004',
  },
  {
    type: '패턴',
    typeCode: 'de_pt_000',
    value: '도트',
    valueCode: 'de_pt_005',
  },
  {
    type: '패턴',
    typeCode: 'de_pt_000',
    value: '애니멀',
    valueCode: 'de_pt_006',
  },
  {
    type: '패턴',
    typeCode: 'de_pt_000',
    value: '플로럴',
    valueCode: 'de_pt_007',
  },
  {
    type: '패턴',
    typeCode: 'de_pt_000',
    value: '트로피칼',
    valueCode: 'de_pt_008',
  },
  {
    type: '패턴',
    typeCode: 'de_pt_000',
    value: '페이즐리',
    valueCode: 'de_pt_009',
  },
  {
    type: '패턴',
    typeCode: 'de_pt_000',
    value: '아가일',
    valueCode: 'de_pt_010',
  },
  {
    type: '패턴',
    typeCode: 'de_pt_000',
    value: '밀리터리',
    valueCode: 'de_pt_011',
  },
  {
    type: '패턴',
    typeCode: 'de_pt_000',
    value: '기타',
    valueCode: 'de_pt_012',
  },
];
